import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Field Logic design system
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#404945",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#707974",
        "outline-variant": "#c0c9c3",
        "surface-tint": "#376757",
        primary: "#003629",
        "on-primary": "#ffffff",
        "primary-container": "#1b4d3e",
        "on-primary-container": "#8abda9",
        "inverse-primary": "#9ed1bd",
        secondary: "#7c5800",
        "on-secondary": "#ffffff",
        "secondary-container": "#fec24a",
        "on-secondary-container": "#715000",
        tertiary: "#4c221c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#673831",
        "on-tertiary-container": "#e4a399",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#baeed9",
        "primary-fixed-dim": "#9ed1bd",
        "on-primary-fixed": "#002117",
        "on-primary-fixed-variant": "#1d4f40",
        "secondary-fixed": "#ffdea7",
        "secondary-fixed-dim": "#f8bd45",
        "on-secondary-fixed": "#271900",
        "on-secondary-fixed-variant": "#5e4200",
        "tertiary-fixed": "#ffdad5",
        "tertiary-fixed-dim": "#fab6ac",
        "on-tertiary-fixed": "#34100b",
        "on-tertiary-fixed-variant": "#693a33",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
        // Brand aliases
        "growth-green": "#1B4D3E",
        "utility-gold": "#D49D26",
        "surface-base": "#F5F1EB",
        "surface-subtle": "#EBE3D5",
        "slate-deep": "#1A1A1A",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "container-max-width": "1280px",
      },
      fontFamily: {
        geist: ["var(--font-geist-sans)", "Geist", "sans-serif"],
        inter: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        // Semantic aliases matching the HTML spec
        "headline-lg": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "headline-md": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "headline-sm": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-mono": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "button-text": ["var(--font-geist-sans)", "Geist", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "button-text": ["16px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      animation: {
        "recording-pulse": "recording-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "ai-shimmer": "ai-shimmer 2s infinite linear",
        "slide-in": "slide-in 0.4s ease-out forwards",
        "error-shake": "error-shake 0.5s cubic-bezier(.36,.07,.19,.97) both",
        bounce: "bounce 1s infinite",
      },
      keyframes: {
        "recording-pulse": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.7", transform: "scale(1.05)" },
        },
        "ai-shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "slide-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "error-shake": {
          "10%, 90%": { transform: "translate3d(-1px, 0, 0)" },
          "20%, 80%": { transform: "translate3d(2px, 0, 0)" },
          "30%, 50%, 70%": { transform: "translate3d(-4px, 0, 0)" },
          "40%, 60%": { transform: "translate3d(4px, 0, 0)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
